const data = [
  {
    fullName: "Nikki Klimkovich",
    gender: "Female",
    jobTitle: "Internal Auditor",
    language: "Tsonga",
    ssn: "792-92-3383",
    money: "$250.53",
  },
  {
    fullName: "Reggie Grandin",
    gender: "Male",
    jobTitle: "Technical Writer",
    language: "Macedonian",
    ssn: "230-73-5179",
    money: "$494.07",
  },
  {
    fullName: "Ave Yekel",
    gender: "Male",
    jobTitle: "Environmental Tech",
    language: "Dari",
    ssn: "296-09-0800",
    money: "$984.69",
  },
  {
    fullName: "Corrie Crackel",
    gender: "Male",
    jobTitle: "Environmental Specialist",
    language: "Gagauz",
    ssn: "326-62-7851",
    money: "$420.04",
  },
  {
    fullName: "Brande Codlin",
    gender: "Female",
    jobTitle: "Quality Engineer",
    language: "Thai",
    ssn: "309-96-0917",
    money: "$693.15",
  },
  {
    fullName: "Rossie Augie",
    gender: "Male",
    jobTitle: "Software Engineer II",
    language: "Belarusian",
    ssn: "746-64-8602",
    money: "$157.49",
  },
  {
    fullName: "Neddy Bleackly",
    gender: "Male",
    jobTitle: "Account Coordinator",
    language: "Dari",
    ssn: "228-25-9384",
    money: "$322.11",
  },
  {
    fullName: "Davie Maffini",
    gender: "Male",
    jobTitle: "Librarian",
    language: "French",
    ssn: "492-63-1385",
    money: "$216.07",
  },
  {
    fullName: "Steward Ebben",
    gender: "Male",
    jobTitle: "Media Manager I",
    language: "Montenegrin",
    ssn: "391-04-1268",
    money: "$483.79",
  },
  {
    fullName: "Dedie Ixor",
    gender: "Female",
    jobTitle: "Accountant III",
    language: "Assamese",
    ssn: "795-63-8402",
    money: "$383.70",
  },
  {
    fullName: "Odette Grigorian",
    gender: "Female",
    jobTitle: "Technical Writer",
    language: "Arabic",
    ssn: "340-64-2084",
    money: "$894.49",
  },
  {
    fullName: "Fin Ivashinnikov",
    gender: "Male",
    jobTitle: "VP Product Management",
    language: "English",
    ssn: "203-80-8771",
    money: "$131.94",
  },
  {
    fullName: "Ashley Rummin",
    gender: "Male",
    jobTitle: "Software Consultant",
    language: "Kannada",
    ssn: "598-45-6995",
    money: "$814.26",
  },
  {
    fullName: "Hannie Middleton",
    gender: "Female",
    jobTitle: "Research Nurse",
    language: "Bosnian",
    ssn: "260-50-3609",
    money: "$69.28",
  },
  {
    fullName: "Celine Tommaseo",
    gender: "Female",
    jobTitle: "Graphic Designer",
    language: "French",
    ssn: "535-17-5579",
    money: "$432.42",
  },
  {
    fullName: "Keefer Crackett",
    gender: "Male",
    jobTitle: "Sales Representative",
    language: "Maltese",
    ssn: "719-86-3748",
    money: "$761.44",
  },
  {
    fullName: "Noell Dudliston",
    gender: "Female",
    jobTitle: "Web Developer IV",
    language: "Armenian",
    ssn: "680-79-9243",
    money: "$46.99",
  },
  {
    fullName: "Roma Testo",
    gender: "Male",
    jobTitle: "Executive Secretary",
    language: "Belarusian",
    ssn: "738-10-3280",
    money: "$112.82",
  },
  {
    fullName: "Letti Lamartine",
    gender: "Female",
    jobTitle: "Speech Pathologist",
    language: "Zulu",
    ssn: "133-36-5623",
    money: "$377.76",
  },
  {
    fullName: "Rurik Heake",
    gender: "Male",
    jobTitle: "Accounting Assistant III",
    language: "Bosnian",
    ssn: "665-69-4865",
    money: "$87.89",
  },
  {
    fullName: "Oliviero Gowans",
    gender: "Male",
    jobTitle: "Staff Accountant III",
    language: "Azeri",
    ssn: "644-74-2369",
    money: "$717.48",
  },
  {
    fullName: "Barney Eakle",
    gender: "Male",
    jobTitle: "Clinical Specialist",
    language: "Albanian",
    ssn: "631-08-3165",
    money: "$924.64",
  },
  {
    fullName: "Torre Dunkerton",
    gender: "Male",
    jobTitle: "Sales Representative",
    language: "Malagasy",
    ssn: "795-34-0933",
    money: "$379.93",
  },
  {
    fullName: "Daveta Sargent",
    gender: "Female",
    jobTitle: "Accounting Assistant IV",
    language: "Greek",
    ssn: "384-63-1655",
    money: "$405.55",
  },
  {
    fullName: "Jeremiah Handford",
    gender: "Male",
    jobTitle: "Project Manager",
    language: "Marathi",
    ssn: "760-51-7509",
    money: "$779.59",
  },
  {
    fullName: "Hammad Lowell",
    gender: "Male",
    jobTitle: "Budget/Accounting Analyst IV",
    language: "Swahili",
    ssn: "233-85-5331",
    money: "$233.07",
  },
  {
    fullName: "Donalt Hazell",
    gender: "Male",
    jobTitle: "Physical Therapy Assistant",
    language: "Somali",
    ssn: "348-16-9124",
    money: "$668.99",
  },
  {
    fullName: "Kameko MacDermand",
    gender: "Female",
    jobTitle: "Desktop Support Technician",
    language: "Hiri Motu",
    ssn: "526-69-6873",
    money: "$955.16",
  },
  {
    fullName: "Vernor Ganford",
    gender: "Male",
    jobTitle: "Financial Advisor",
    language: "Tok Pisin",
    ssn: "660-72-9190",
    money: "$185.53",
  },
  {
    fullName: "Hewitt Vedntyev",
    gender: "Male",
    jobTitle: "Chemical Engineer",
    language: "Dari",
    ssn: "519-16-0290",
    money: "$541.26",
  },
  {
    fullName: "Dasha Costello",
    gender: "Female",
    jobTitle: "Community Outreach Specialist",
    language: "Bislama",
    ssn: "614-88-6083",
    money: "$800.47",
  },
  {
    fullName: "Farleigh Hume",
    gender: "Male",
    jobTitle: "Senior Editor",
    language: "Danish",
    ssn: "674-91-0452",
    money: "$22.17",
  },
  {
    fullName: "Shamus Toulson",
    gender: "Male",
    jobTitle: "Pharmacist",
    language: "Azeri",
    ssn: "451-75-3115",
    money: "$950.85",
  },
  {
    fullName: "Drake Grim",
    gender: "Male",
    jobTitle: "Editor",
    language: "Kashmiri",
    ssn: "396-77-1917",
    money: "$751.37",
  },
  {
    fullName: "Barrett Seggie",
    gender: "Male",
    jobTitle: "Biostatistician III",
    language: "Bislama",
    ssn: "631-41-9056",
    money: "$412.21",
  },
  {
    fullName: "Romonda Espine",
    gender: "Female",
    jobTitle: "Engineer IV",
    language: "Tajik",
    ssn: "897-08-2659",
    money: "$89.32",
  },
  {
    fullName: "Tisha McIlvaney",
    gender: "Female",
    jobTitle: "Paralegal",
    language: "Sotho",
    ssn: "757-67-0703",
    money: "$976.12",
  },
  {
    fullName: "Quinlan Comizzoli",
    gender: "Male",
    jobTitle: "Clinical Specialist",
    language: "Khmer",
    ssn: "177-70-0360",
    money: "$972.89",
  },
  {
    fullName: "Remy Feavearyear",
    gender: "Female",
    jobTitle: "Nurse",
    language: "Malayalam",
    ssn: "227-65-5096",
    money: "$929.57",
  },
  {
    fullName: "Craig Dudbridge",
    gender: "Male",
    jobTitle: "Product Engineer",
    language: "Dutch",
    ssn: "724-86-0177",
    money: "$55.31",
  },
  {
    fullName: "Felice Aldren",
    gender: "Male",
    jobTitle: "Budget/Accounting Analyst II",
    language: "Māori",
    ssn: "448-55-3603",
    money: "$432.88",
  },
  {
    fullName: "Jermain Pasby",
    gender: "Male",
    jobTitle: "Senior Financial Analyst",
    language: "Indonesian",
    ssn: "591-03-1096",
    money: "$678.29",
  },
  {
    fullName: "Giacobo Bagniuk",
    gender: "Male",
    jobTitle: "Senior Sales Associate",
    language: "Latvian",
    ssn: "243-65-5794",
    money: "$333.29",
  },
  {
    fullName: "Charlton Jordine",
    gender: "Male",
    jobTitle: "Office Assistant IV",
    language: "Maltese",
    ssn: "672-59-8034",
    money: "$496.88",
  },
  {
    fullName: "Tine Moorman",
    gender: "Female",
    jobTitle: "Account Representative II",
    language: "Zulu",
    ssn: "641-39-3414",
    money: "$456.43",
  },
  {
    fullName: "Vanya Gorsse",
    gender: "Male",
    jobTitle: "Social Worker",
    language: "Tetum",
    ssn: "191-61-2956",
    money: "$721.21",
  },
  {
    fullName: "Braden Marusic",
    gender: "Male",
    jobTitle: "Media Manager III",
    language: "Zulu",
    ssn: "431-04-5123",
    money: "$601.33",
  },
  {
    fullName: "Roarke Lamps",
    gender: "Male",
    jobTitle: "Senior Developer",
    language: "Tswana",
    ssn: "826-18-3949",
    money: "$470.56",
  },
  {
    fullName: "Graig Kenryd",
    gender: "Male",
    jobTitle: "Assistant Professor",
    language: "Armenian",
    ssn: "190-90-8554",
    money: "$942.99",
  },
  {
    fullName: "Ashby Harrington",
    gender: "Male",
    jobTitle: "Assistant Professor",
    language: "Kannada",
    ssn: "515-23-9438",
    money: "$153.61",
  },
  {
    fullName: "Pembroke Wiffield",
    gender: "Male",
    jobTitle: "Executive Secretary",
    language: "Azeri",
    ssn: "758-19-7966",
    money: "$521.73",
  },
  {
    fullName: "Quincey Lightbody",
    gender: "Male",
    jobTitle: "Programmer IV",
    language: "Armenian",
    ssn: "675-72-0271",
    money: "$420.51",
  },
  {
    fullName: "Cheston Lavallie",
    gender: "Male",
    jobTitle: "Legal Assistant",
    language: "Romanian",
    ssn: "674-21-6586",
    money: "$694.20",
  },
  {
    fullName: "Naomi Cluitt",
    gender: "Female",
    jobTitle: "Computer Systems Analyst IV",
    language: "Mongolian",
    ssn: "302-81-0840",
    money: "$717.54",
  },
  {
    fullName: "Anjanette Water",
    gender: "Female",
    jobTitle: "Programmer IV",
    language: "West Frisian",
    ssn: "862-25-4824",
    money: "$339.40",
  },
  {
    fullName: "Tracy Garrique",
    gender: "Female",
    jobTitle: "Community Outreach Specialist",
    language: "Kyrgyz",
    ssn: "489-57-9741",
    money: "$499.77",
  },
  {
    fullName: "Philippe Peerman",
    gender: "Female",
    jobTitle: "Paralegal",
    language: "Kashmiri",
    ssn: "630-43-4853",
    money: "$826.92",
  },
  {
    fullName: "Roxy Lockhart",
    gender: "Female",
    jobTitle: "Information Systems Manager",
    language: "Afrikaans",
    ssn: "536-86-8839",
    money: "$227.98",
  },
  {
    fullName: "Marice Churn",
    gender: "Female",
    jobTitle: "Marketing Manager",
    language: "Hebrew",
    ssn: "593-27-6466",
    money: "$43.26",
  },
  {
    fullName: "Ariel Champneys",
    gender: "Female",
    jobTitle: "Help Desk Technician",
    language: "Czech",
    ssn: "829-62-9865",
    money: "$171.36",
  },
  {
    fullName: "Dru Breissan",
    gender: "Female",
    jobTitle: "Software Test Engineer I",
    language: "Bislama",
    ssn: "165-24-4553",
    money: "$465.69",
  },
  {
    fullName: "Lindsy Leggon",
    gender: "Female",
    jobTitle: "Quality Engineer",
    language: "Fijian",
    ssn: "858-95-0998",
    money: "$477.11",
  },
  {
    fullName: "Aubrie Kullmann",
    gender: "Female",
    jobTitle: "Business Systems Development Analyst",
    language: "Dhivehi",
    ssn: "864-60-9575",
    money: "$371.98",
  },
  {
    fullName: "Ardelis Pidgeley",
    gender: "Female",
    jobTitle: "Structural Analysis Engineer",
    language: "Punjabi",
    ssn: "279-43-4333",
    money: "$7.29",
  },
  {
    fullName: "Sydney Felix",
    gender: "Male",
    jobTitle: "Financial Analyst",
    language: "Haitian Creole",
    ssn: "647-50-6594",
    money: "$612.23",
  },
  {
    fullName: "Candy Lackey",
    gender: "Female",
    jobTitle: "Environmental Tech",
    language: "Swati",
    ssn: "499-59-6590",
    money: "$991.18",
  },
  {
    fullName: "Angie Banck",
    gender: "Male",
    jobTitle: "Environmental Tech",
    language: "Māori",
    ssn: "338-10-1875",
    money: "$46.88",
  },
  {
    fullName: "Kerianne Kopisch",
    gender: "Female",
    jobTitle: "Tax Accountant",
    language: "Malay",
    ssn: "700-83-4772",
    money: "$727.79",
  },
  {
    fullName: "Dominique Valens-Smith",
    gender: "Female",
    jobTitle: "Software Consultant",
    language: "Guaraní",
    ssn: "660-10-5196",
    money: "$658.68",
  },
  {
    fullName: "Krishna Bette",
    gender: "Male",
    jobTitle: "Nurse",
    language: "French",
    ssn: "539-48-4047",
    money: "$655.93",
  },
  {
    fullName: "Micki Deniset",
    gender: "Female",
    jobTitle: "Junior Executive",
    language: "Japanese",
    ssn: "165-47-7483",
    money: "$95.55",
  },
  {
    fullName: "Karrie Toderini",
    gender: "Female",
    jobTitle: "Software Engineer III",
    language: "Oriya",
    ssn: "720-61-0132",
    money: "$279.18",
  },
  {
    fullName: "Bartie O'Giany",
    gender: "Male",
    jobTitle: "Programmer Analyst III",
    language: "New Zealand Sign Language",
    ssn: "245-01-1281",
    money: "$791.70",
  },
  {
    fullName: "Tamqrah Wittleton",
    gender: "Female",
    jobTitle: "VP Product Management",
    language: "Georgian",
    ssn: "860-39-6666",
    money: "$282.15",
  },
  {
    fullName: "Siouxie Sexty",
    gender: "Female",
    jobTitle: "Compensation Analyst",
    language: "Indonesian",
    ssn: "696-05-8391",
    money: "$395.17",
  },
  {
    fullName: "Lotti Streatley",
    gender: "Female",
    jobTitle: "Office Assistant IV",
    language: "Bosnian",
    ssn: "669-37-9434",
    money: "$323.12",
  },
  {
    fullName: "Alexander Asquith",
    gender: "Male",
    jobTitle: "Associate Professor",
    language: "Hungarian",
    ssn: "618-18-7231",
    money: "$651.86",
  },
  {
    fullName: "Mackenzie Reeves",
    gender: "Male",
    jobTitle: "Senior Cost Accountant",
    language: "Hiri Motu",
    ssn: "516-71-6444",
    money: "$360.53",
  },
  {
    fullName: "Margo Doxsey",
    gender: "Female",
    jobTitle: "Occupational Therapist",
    language: "Afrikaans",
    ssn: "223-52-3494",
    money: "$628.43",
  },
  {
    fullName: "Xerxes Scading",
    gender: "Male",
    jobTitle: "Account Executive",
    language: "English",
    ssn: "536-86-1073",
    money: "$607.72",
  },
  {
    fullName: "Cassy Dubose",
    gender: "Female",
    jobTitle: "Software Test Engineer IV",
    language: "English",
    ssn: "747-38-4527",
    money: "$313.90",
  },
  {
    fullName: "Beniamino Ruben",
    gender: "Male",
    jobTitle: "Design Engineer",
    language: "Bulgarian",
    ssn: "746-73-9613",
    money: "$282.02",
  },
  {
    fullName: "Meggie Dulanty",
    gender: "Female",
    jobTitle: "Health Coach II",
    language: "Kurdish",
    ssn: "763-57-6917",
    money: "$464.32",
  },
  {
    fullName: "Chevalier Dartan",
    gender: "Male",
    jobTitle: "Product Engineer",
    language: "Burmese",
    ssn: "499-34-5591",
    money: "$253.48",
  },
  {
    fullName: "Bernhard Ponting",
    gender: "Male",
    jobTitle: "Quality Engineer",
    language: "Gagauz",
    ssn: "112-34-7240",
    money: "$173.18",
  },
  {
    fullName: "Roland Pelerin",
    gender: "Male",
    jobTitle: "Social Worker",
    language: "Latvian",
    ssn: "423-90-6887",
    money: "$443.47",
  },
  {
    fullName: "Karon Winfindale",
    gender: "Female",
    jobTitle: "Structural Analysis Engineer",
    language: "Dutch",
    ssn: "208-81-9570",
    money: "$406.60",
  },
  {
    fullName: "Sorcha Abramamovh",
    gender: "Female",
    jobTitle: "Human Resources Assistant I",
    language: "Malay",
    ssn: "833-70-4652",
    money: "$601.51",
  },
  {
    fullName: "Buck Caris",
    gender: "Male",
    jobTitle: "Food Chemist",
    language: "Kyrgyz",
    ssn: "602-68-1428",
    money: "$573.09",
  },
  {
    fullName: "Waring Riccelli",
    gender: "Male",
    jobTitle: "Marketing Manager",
    language: "Bengali",
    ssn: "690-46-4934",
    money: "$104.05",
  },
  {
    fullName: "Fancy Loutheane",
    gender: "Female",
    jobTitle: "Staff Scientist",
    language: "Khmer",
    ssn: "479-45-4953",
    money: "$245.84",
  },
  {
    fullName: "Cleve Lydiate",
    gender: "Male",
    jobTitle: "Administrative Officer",
    language: "Japanese",
    ssn: "540-59-1910",
    money: "$358.49",
  },
  {
    fullName: "Fairleigh Stoakes",
    gender: "Male",
    jobTitle: "Assistant Media Planner",
    language: "Haitian Creole",
    ssn: "621-88-4691",
    money: "$464.03",
  },
  {
    fullName: "Lora Brew",
    gender: "Female",
    jobTitle: "Marketing Assistant",
    language: "Finnish",
    ssn: "208-48-9890",
    money: "$851.16",
  },
  {
    fullName: "Sollie Ranson",
    gender: "Male",
    jobTitle: "Financial Analyst",
    language: "Khmer",
    ssn: "681-43-0166",
    money: "$599.30",
  },
  {
    fullName: "Raf Chaston",
    gender: "Female",
    jobTitle: "Account Representative I",
    language: "Lithuanian",
    ssn: "333-08-6861",
    money: "$228.16",
  },
  {
    fullName: "Ollie Yakovitch",
    gender: "Male",
    jobTitle: "Compensation Analyst",
    language: "Malagasy",
    ssn: "379-85-1121",
    money: "$111.51",
  },
  {
    fullName: "Ambrosius Robic",
    gender: "Male",
    jobTitle: "Executive Secretary",
    language: "Hiri Motu",
    ssn: "353-67-1962",
    money: "$728.37",
  },
  {
    fullName: "Ferdinanda Allett",
    gender: "Female",
    jobTitle: "Data Coordinator",
    language: "Mongolian",
    ssn: "237-02-2050",
    money: "$633.36",
  },
  {
    fullName: "Hebert Casterou",
    gender: "Male",
    jobTitle: "Assistant Manager",
    language: "English",
    ssn: "303-82-0915",
    money: "$285.51",
  },
  {
    fullName: "Raine Casacchia",
    gender: "Female",
    jobTitle: "Technical Writer",
    language: "French",
    ssn: "561-60-1052",
    money: "$160.88",
  },
  {
    fullName: "Aloysius Trent",
    gender: "Male",
    jobTitle: "Payment Adjustment Coordinator",
    language: "Finnish",
    ssn: "606-46-2569",
    money: "$152.07",
  },
  {
    fullName: "Harmon Pymar",
    gender: "Male",
    jobTitle: "VP Marketing",
    language: "Dzongkha",
    ssn: "809-47-1517",
    money: "$926.51",
  },
  {
    fullName: "Harwilll Scherme",
    gender: "Male",
    jobTitle: "Web Developer I",
    language: "Amharic",
    ssn: "848-62-0182",
    money: "$298.11",
  },
  {
    fullName: "Adams Barthelemy",
    gender: "Male",
    jobTitle: "Assistant Manager",
    language: "Polish",
    ssn: "521-43-6125",
    money: "$218.26",
  },
  {
    fullName: "Cyndy Skeermer",
    gender: "Female",
    jobTitle: "Professor",
    language: "Georgian",
    ssn: "179-18-7966",
    money: "$999.93",
  },
  {
    fullName: "Torrance Jelleman",
    gender: "Male",
    jobTitle: "Account Coordinator",
    language: "Bislama",
    ssn: "449-23-0073",
    money: "$141.30",
  },
  {
    fullName: "Bard Dolley",
    gender: "Male",
    jobTitle: "Human Resources Manager",
    language: "Malay",
    ssn: "320-54-3663",
    money: "$770.13",
  },
  {
    fullName: "Savina Bennison",
    gender: "Female",
    jobTitle: "Senior Quality Engineer",
    language: "Dzongkha",
    ssn: "636-65-4672",
    money: "$613.44",
  },
  {
    fullName: "Noel Bonsale",
    gender: "Female",
    jobTitle: "Recruiter",
    language: "Chinese",
    ssn: "622-47-9945",
    money: "$768.09",
  },
  {
    fullName: "Nalani Howling",
    gender: "Female",
    jobTitle: "Legal Assistant",
    language: "German",
    ssn: "323-27-5045",
    money: "$694.61",
  },
  {
    fullName: "Esme Vallens",
    gender: "Female",
    jobTitle: "Budget/Accounting Analyst I",
    language: "Filipino",
    ssn: "502-96-1388",
    money: "$364.22",
  },
  {
    fullName: "Melody Tyhurst",
    gender: "Female",
    jobTitle: "Marketing Manager",
    language: "Māori",
    ssn: "633-32-3969",
    money: "$703.46",
  },
  {
    fullName: "Daniella Gouldsmith",
    gender: "Female",
    jobTitle: "Senior Editor",
    language: "Oriya",
    ssn: "728-25-8073",
    money: "$526.68",
  },
  {
    fullName: "Jyoti Cunniffe",
    gender: "Female",
    jobTitle: "Quality Control Specialist",
    language: "Hungarian",
    ssn: "127-84-3032",
    money: "$651.65",
  },
  {
    fullName: "Jessa Shiliton",
    gender: "Female",
    jobTitle: "Tax Accountant",
    language: "Guaraní",
    ssn: "376-91-4935",
    money: "$67.82",
  },
  {
    fullName: "Elysha Cheyenne",
    gender: "Female",
    jobTitle: "VP Quality Control",
    language: "Papiamento",
    ssn: "878-95-8585",
    money: "$710.15",
  },
  {
    fullName: "Carson Bigby",
    gender: "Male",
    jobTitle: "Physical Therapy Assistant",
    language: "Malay",
    ssn: "248-68-4685",
    money: "$985.70",
  },
  {
    fullName: "Wye Gilhooley",
    gender: "Male",
    jobTitle: "Nurse",
    language: "Finnish",
    ssn: "319-01-2645",
    money: "$208.98",
  },
  {
    fullName: "Milissent Romagosa",
    gender: "Female",
    jobTitle: "Software Consultant",
    language: "Tetum",
    ssn: "201-18-3318",
    money: "$97.85",
  },
  {
    fullName: "Loleta Kubista",
    gender: "Female",
    jobTitle: "Social Worker",
    language: "Thai",
    ssn: "891-51-4903",
    money: "$129.16",
  },
  {
    fullName: "Niccolo Branscomb",
    gender: "Male",
    jobTitle: "Marketing Assistant",
    language: "Dzongkha",
    ssn: "735-69-8635",
    money: "$27.65",
  },
  {
    fullName: "Regine Manneville",
    gender: "Female",
    jobTitle: "VP Sales",
    language: "Armenian",
    ssn: "335-30-6121",
    money: "$368.73",
  },
  {
    fullName: "Huntley Mulkerrins",
    gender: "Male",
    jobTitle: "VP Quality Control",
    language: "Somali",
    ssn: "875-81-5500",
    money: "$335.78",
  },
  {
    fullName: "Charisse Collcutt",
    gender: "Female",
    jobTitle: "Editor",
    language: "Tajik",
    ssn: "516-29-0889",
    money: "$156.40",
  },
  {
    fullName: "Ernst Fache",
    gender: "Male",
    jobTitle: "Food Chemist",
    language: "Finnish",
    ssn: "665-96-3722",
    money: "$75.51",
  },
  {
    fullName: "Lily Cornner",
    gender: "Female",
    jobTitle: "Executive Secretary",
    language: "Icelandic",
    ssn: "246-04-6836",
    money: "$698.25",
  },
  {
    fullName: "Ariel Pley",
    gender: "Female",
    jobTitle: "Research Associate",
    language: "Yiddish",
    ssn: "266-38-8812",
    money: "$168.48",
  },
  {
    fullName: "Lynne Sacaze",
    gender: "Female",
    jobTitle: "Cost Accountant",
    language: "Malay",
    ssn: "198-20-4587",
    money: "$439.40",
  },
  {
    fullName: "Rainer Rodie",
    gender: "Male",
    jobTitle: "Computer Systems Analyst IV",
    language: "Catalan",
    ssn: "847-01-3018",
    money: "$59.18",
  },
  {
    fullName: "Mitzi Eyckelbeck",
    gender: "Female",
    jobTitle: "Nurse Practicioner",
    language: "Indonesian",
    ssn: "577-64-1501",
    money: "$155.08",
  },
  {
    fullName: "Isabella Henrichs",
    gender: "Female",
    jobTitle: "Payment Adjustment Coordinator",
    language: "Tamil",
    ssn: "399-44-1981",
    money: "$280.21",
  },
  {
    fullName: "Odille Gaythor",
    gender: "Female",
    jobTitle: "Pharmacist",
    language: "Bengali",
    ssn: "346-04-7171",
    money: "$228.46",
  },
  {
    fullName: "Kevon Gellert",
    gender: "Male",
    jobTitle: "VP Product Management",
    language: "Gagauz",
    ssn: "173-77-8218",
    money: "$64.93",
  },
  {
    fullName: "Gratiana Grzeszczyk",
    gender: "Female",
    jobTitle: "Help Desk Technician",
    language: "Japanese",
    ssn: "772-34-0113",
    money: "$657.40",
  },
  {
    fullName: "Em Brabyn",
    gender: "Female",
    jobTitle: "Executive Secretary",
    language: "Danish",
    ssn: "113-39-4718",
    money: "$33.18",
  },
  {
    fullName: "Jan Lundon",
    gender: "Female",
    jobTitle: "Executive Secretary",
    language: "Kazakh",
    ssn: "474-72-1516",
    money: "$76.08",
  },
  {
    fullName: "Cobby McCloy",
    gender: "Male",
    jobTitle: "VP Sales",
    language: "Yiddish",
    ssn: "389-89-4134",
    money: "$750.61",
  },
  {
    fullName: "Reube Germain",
    gender: "Male",
    jobTitle: "Data Coordinator",
    language: "Northern Sotho",
    ssn: "355-13-6803",
    money: "$827.71",
  },
  {
    fullName: "Salmon Alessandrelli",
    gender: "Male",
    jobTitle: "Mechanical Systems Engineer",
    language: "Tsonga",
    ssn: "789-59-5518",
    money: "$559.96",
  },
  {
    fullName: "Monte Lovering",
    gender: "Male",
    jobTitle: "Sales Representative",
    language: "Malayalam",
    ssn: "187-72-2361",
    money: "$972.75",
  },
  {
    fullName: "Kelcie Nettleship",
    gender: "Female",
    jobTitle: "Computer Systems Analyst III",
    language: "Catalan",
    ssn: "758-95-6974",
    money: "$423.46",
  },
  {
    fullName: "Dix Stewartson",
    gender: "Female",
    jobTitle: "Teacher",
    language: "Romanian",
    ssn: "759-24-9881",
    money: "$791.29",
  },
  {
    fullName: "Todd Beaconsall",
    gender: "Male",
    jobTitle: "Chief Design Engineer",
    language: "Armenian",
    ssn: "781-52-7106",
    money: "$526.80",
  },
  {
    fullName: "Mendy Dinjes",
    gender: "Male",
    jobTitle: "Office Assistant III",
    language: "Norwegian",
    ssn: "270-96-5505",
    money: "$800.05",
  },
  {
    fullName: "Carmine Timbs",
    gender: "Female",
    jobTitle: "Programmer III",
    language: "Croatian",
    ssn: "171-35-4537",
    money: "$260.26",
  },
  {
    fullName: "Arliene Passman",
    gender: "Female",
    jobTitle: "Structural Engineer",
    language: "Chinese",
    ssn: "497-88-5007",
    money: "$116.44",
  },
  {
    fullName: "Glen Rangeley",
    gender: "Female",
    jobTitle: "Budget/Accounting Analyst III",
    language: "Swahili",
    ssn: "617-78-0212",
    money: "$553.65",
  },
  {
    fullName: "Donnajean Rampley",
    gender: "Female",
    jobTitle: "Executive Secretary",
    language: "Punjabi",
    ssn: "679-79-2473",
    money: "$152.18",
  },
  {
    fullName: "Ivett Mobley",
    gender: "Female",
    jobTitle: "Product Engineer",
    language: "Persian",
    ssn: "648-38-0744",
    money: "$270.98",
  },
  {
    fullName: "Drucie Orsay",
    gender: "Female",
    jobTitle: "Pharmacist",
    language: "Hiri Motu",
    ssn: "310-70-5188",
    money: "$744.41",
  },
  {
    fullName: "Javier Elwel",
    gender: "Male",
    jobTitle: "Health Coach III",
    language: "Pashto",
    ssn: "711-77-8407",
    money: "$633.72",
  },
  {
    fullName: "Tiffani McCarty",
    gender: "Female",
    jobTitle: "Senior Financial Analyst",
    language: "Somali",
    ssn: "686-19-9634",
    money: "$255.25",
  },
  {
    fullName: "Farrel Epple",
    gender: "Male",
    jobTitle: "Programmer II",
    language: "Aymara",
    ssn: "542-86-1522",
    money: "$385.22",
  },
  {
    fullName: "Eilis Knutsen",
    gender: "Female",
    jobTitle: "Recruiting Manager",
    language: "Chinese",
    ssn: "516-35-5802",
    money: "$505.46",
  },
  {
    fullName: "Cora Gahagan",
    gender: "Female",
    jobTitle: "Geologist III",
    language: "Tetum",
    ssn: "517-18-3212",
    money: "$868.61",
  },
  {
    fullName: "Caesar Ledgerton",
    gender: "Male",
    jobTitle: "VP Product Management",
    language: "English",
    ssn: "143-29-2654",
    money: "$204.97",
  },
  {
    fullName: "Jania Cullon",
    gender: "Female",
    jobTitle: "Sales Associate",
    language: "Zulu",
    ssn: "288-36-2033",
    money: "$651.38",
  },
  {
    fullName: "Pavlov Gollin",
    gender: "Male",
    jobTitle: "Staff Accountant IV",
    language: "Swedish",
    ssn: "882-42-4650",
    money: "$873.91",
  },
  {
    fullName: "Luce McGarry",
    gender: "Female",
    jobTitle: "Developer III",
    language: "Mongolian",
    ssn: "659-35-6714",
    money: "$638.46",
  },
  {
    fullName: "Uriah Abrami",
    gender: "Male",
    jobTitle: "Librarian",
    language: "Oriya",
    ssn: "146-27-2788",
    money: "$95.20",
  },
  {
    fullName: "Alisha Djurevic",
    gender: "Female",
    jobTitle: "GIS Technical Architect",
    language: "Punjabi",
    ssn: "449-73-4227",
    money: "$869.22",
  },
  {
    fullName: "Veronique Vaines",
    gender: "Female",
    jobTitle: "Biostatistician I",
    language: "Oriya",
    ssn: "167-28-2628",
    money: "$299.15",
  },
  {
    fullName: "Jordana Davidovits",
    gender: "Female",
    jobTitle: "Senior Editor",
    language: "Swedish",
    ssn: "233-67-7763",
    money: "$35.91",
  },
  {
    fullName: "Lauritz Meharg",
    gender: "Male",
    jobTitle: "Tax Accountant",
    language: "Spanish",
    ssn: "468-58-9588",
    money: "$969.72",
  },
  {
    fullName: "Beret Heilds",
    gender: "Female",
    jobTitle: "Media Manager II",
    language: "Luxembourgish",
    ssn: "619-20-9921",
    money: "$360.30",
  },
  {
    fullName: "Lainey Tower",
    gender: "Female",
    jobTitle: "Food Chemist",
    language: "Montenegrin",
    ssn: "762-30-6217",
    money: "$984.68",
  },
  {
    fullName: "Fey Orange",
    gender: "Female",
    jobTitle: "Project Manager",
    language: "Persian",
    ssn: "504-10-3505",
    money: "$893.24",
  },
  {
    fullName: "Monte Leads",
    gender: "Male",
    jobTitle: "Structural Engineer",
    language: "Burmese",
    ssn: "537-96-9966",
    money: "$243.27",
  },
  {
    fullName: "Blakeley Jendrich",
    gender: "Female",
    jobTitle: "Recruiter",
    language: "Irish Gaelic",
    ssn: "721-93-1669",
    money: "$774.32",
  },
  {
    fullName: "Olivier Yepiskov",
    gender: "Male",
    jobTitle: "Executive Secretary",
    language: "Belarusian",
    ssn: "822-95-6886",
    money: "$823.32",
  },
  {
    fullName: "Norbert Dodshon",
    gender: "Male",
    jobTitle: "Biostatistician III",
    language: "Indonesian",
    ssn: "227-14-5479",
    money: "$155.76",
  },
  {
    fullName: "Camella Shenley",
    gender: "Female",
    jobTitle: "Accountant IV",
    language: "Tok Pisin",
    ssn: "705-90-0815",
    money: "$294.28",
  },
  {
    fullName: "Taylor Bickle",
    gender: "Male",
    jobTitle: "Account Representative IV",
    language: "Nepali",
    ssn: "516-08-0591",
    money: "$905.23",
  },
  {
    fullName: "Vince De Cleen",
    gender: "Male",
    jobTitle: "Human Resources Assistant I",
    language: "Belarusian",
    ssn: "372-75-4356",
    money: "$341.06",
  },
  {
    fullName: "Filbert Brogden",
    gender: "Male",
    jobTitle: "Systems Administrator I",
    language: "Catalan",
    ssn: "194-91-6293",
    money: "$447.07",
  },
  {
    fullName: "Aldous Antyshev",
    gender: "Male",
    jobTitle: "Business Systems Development Analyst",
    language: "Malayalam",
    ssn: "313-97-5342",
    money: "$118.72",
  },
  {
    fullName: "Jodee Ekkel",
    gender: "Female",
    jobTitle: "Paralegal",
    language: "Icelandic",
    ssn: "281-29-5292",
    money: "$471.52",
  },
  {
    fullName: "Bonnibelle Edmonds",
    gender: "Female",
    jobTitle: "Financial Analyst",
    language: "Malayalam",
    ssn: "475-49-7107",
    money: "$905.19",
  },
  {
    fullName: "Giorgio Pidler",
    gender: "Male",
    jobTitle: "Senior Quality Engineer",
    language: "Haitian Creole",
    ssn: "734-04-4091",
    money: "$718.60",
  },
  {
    fullName: "Kendal Neller",
    gender: "Male",
    jobTitle: "Data Coordinator",
    language: "Hindi",
    ssn: "721-30-4384",
    money: "$761.90",
  },
  {
    fullName: "Rafa Rapp",
    gender: "Female",
    jobTitle: "Database Administrator IV",
    language: "Bislama",
    ssn: "188-68-4264",
    money: "$281.66",
  },
  {
    fullName: "Mabelle Jozefczak",
    gender: "Female",
    jobTitle: "Paralegal",
    language: "Somali",
    ssn: "748-28-3202",
    money: "$862.77",
  },
  {
    fullName: "Inger Morfell",
    gender: "Female",
    jobTitle: "Project Manager",
    language: "Romanian",
    ssn: "893-09-7080",
    money: "$912.70",
  },
  {
    fullName: "Olenolin Renforth",
    gender: "Male",
    jobTitle: "Senior Developer",
    language: "Amharic",
    ssn: "495-67-1303",
    money: "$176.51",
  },
  {
    fullName: "Renata Gavrielly",
    gender: "Female",
    jobTitle: "Assistant Manager",
    language: "Moldovan",
    ssn: "874-77-9866",
    money: "$536.21",
  },
  {
    fullName: "Brocky Lowmass",
    gender: "Male",
    jobTitle: "Analyst Programmer",
    language: "Tamil",
    ssn: "390-10-5831",
    money: "$912.24",
  },
  {
    fullName: "Dulcinea Fosbraey",
    gender: "Female",
    jobTitle: "VP Accounting",
    language: "Kannada",
    ssn: "835-31-6166",
    money: "$371.84",
  },
  {
    fullName: "Kimble Ferronel",
    gender: "Male",
    jobTitle: "Assistant Professor",
    language: "Mongolian",
    ssn: "849-21-3408",
    money: "$601.34",
  },
  {
    fullName: "Dallon Wyldbore",
    gender: "Male",
    jobTitle: "Structural Engineer",
    language: "Finnish",
    ssn: "689-22-8720",
    money: "$272.75",
  },
  {
    fullName: "Hyacinthie Cesaric",
    gender: "Female",
    jobTitle: "Research Assistant II",
    language: "Yiddish",
    ssn: "621-48-4958",
    money: "$21.69",
  },
  {
    fullName: "Johnathon Choffin",
    gender: "Male",
    jobTitle: "Product Engineer",
    language: "Afrikaans",
    ssn: "327-87-2625",
    money: "$352.20",
  },
  {
    fullName: "Dougy Taree",
    gender: "Male",
    jobTitle: "Assistant Manager",
    language: "West Frisian",
    ssn: "533-21-8097",
    money: "$641.11",
  },
  {
    fullName: "Alika Pleavin",
    gender: "Female",
    jobTitle: "Computer Systems Analyst II",
    language: "Kazakh",
    ssn: "407-56-7465",
    money: "$358.56",
  },
  {
    fullName: "Wanids Twyning",
    gender: "Female",
    jobTitle: "Account Representative III",
    language: "Georgian",
    ssn: "592-49-9098",
    money: "$92.47",
  },
  {
    fullName: "Godfrey Demchen",
    gender: "Male",
    jobTitle: "Sales Representative",
    language: "Tswana",
    ssn: "770-16-2825",
    money: "$366.56",
  },
  {
    fullName: "Mickie Tickle",
    gender: "Female",
    jobTitle: "Professor",
    language: "Dari",
    ssn: "814-07-6195",
    money: "$810.41",
  },
  {
    fullName: "Launce Yukhnevich",
    gender: "Male",
    jobTitle: "Software Test Engineer II",
    language: "Hindi",
    ssn: "335-27-0273",
    money: "$299.99",
  },
  {
    fullName: "Celisse Sissot",
    gender: "Female",
    jobTitle: "Assistant Manager",
    language: "Thai",
    ssn: "372-46-4913",
    money: "$991.76",
  },
  {
    fullName: "Feodor Najera",
    gender: "Male",
    jobTitle: "Sales Associate",
    language: "Bislama",
    ssn: "681-99-4033",
    money: "$609.85",
  },
  {
    fullName: "Patti Beck",
    gender: "Female",
    jobTitle: "Assistant Manager",
    language: "Tok Pisin",
    ssn: "667-28-5640",
    money: "$145.04",
  },
  {
    fullName: "Bay Mackiewicz",
    gender: "Male",
    jobTitle: "Desktop Support Technician",
    language: "German",
    ssn: "885-70-4392",
    money: "$241.40",
  },
  {
    fullName: "Alick Paddeley",
    gender: "Male",
    jobTitle: "Administrative Officer",
    language: "Estonian",
    ssn: "873-82-3417",
    money: "$424.51",
  },
  {
    fullName: "Monroe Bentame",
    gender: "Male",
    jobTitle: "Analog Circuit Design manager",
    language: "Lao",
    ssn: "491-95-1056",
    money: "$302.31",
  },
  {
    fullName: "Del Wogan",
    gender: "Female",
    jobTitle: "VP Accounting",
    language: "Kazakh",
    ssn: "300-02-2431",
    money: "$643.43",
  },
  {
    fullName: "Marie-ann Wahncke",
    gender: "Female",
    jobTitle: "Social Worker",
    language: "Telugu",
    ssn: "144-63-0038",
    money: "$902.18",
  },
  {
    fullName: "Westley Androli",
    gender: "Male",
    jobTitle: "Mechanical Systems Engineer",
    language: "Nepali",
    ssn: "310-19-2379",
    money: "$443.68",
  },
  {
    fullName: "Randall Humpherston",
    gender: "Male",
    jobTitle: "Editor",
    language: "Tswana",
    ssn: "272-63-2827",
    money: "$528.83",
  },
  {
    fullName: "Luciana Wandrich",
    gender: "Female",
    jobTitle: "Web Developer III",
    language: "Malay",
    ssn: "179-29-9671",
    money: "$789.21",
  },
  {
    fullName: "Woodrow O'Shaughnessy",
    gender: "Male",
    jobTitle: "Graphic Designer",
    language: "Dhivehi",
    ssn: "274-51-6924",
    money: "$724.05",
  },
  {
    fullName: "Jeanette Grigori",
    gender: "Female",
    jobTitle: "Clinical Specialist",
    language: "Indonesian",
    ssn: "665-24-8222",
    money: "$171.38",
  },
  {
    fullName: "Deva Filppetti",
    gender: "Female",
    jobTitle: "VP Quality Control",
    language: "Swedish",
    ssn: "355-19-2599",
    money: "$21.27",
  },
  {
    fullName: "Danya Wakelin",
    gender: "Female",
    jobTitle: "Community Outreach Specialist",
    language: "Greek",
    ssn: "497-24-3588",
    money: "$807.06",
  },
  {
    fullName: "Evyn Krolle",
    gender: "Male",
    jobTitle: "Actuary",
    language: "Aymara",
    ssn: "674-84-7825",
    money: "$73.04",
  },
  {
    fullName: "Jelene Southern",
    gender: "Female",
    jobTitle: "Senior Developer",
    language: "Oriya",
    ssn: "204-23-4917",
    money: "$832.99",
  },
  {
    fullName: "Rodolfo Crepin",
    gender: "Male",
    jobTitle: "Quality Engineer",
    language: "Haitian Creole",
    ssn: "595-18-0330",
    money: "$739.89",
  },
  {
    fullName: "Hamlen Kinnett",
    gender: "Male",
    jobTitle: "Sales Representative",
    language: "Maltese",
    ssn: "341-85-7372",
    money: "$925.00",
  },
  {
    fullName: "Rossie Laux",
    gender: "Male",
    jobTitle: "Safety Technician IV",
    language: "Indonesian",
    ssn: "150-95-4282",
    money: "$140.13",
  },
  {
    fullName: "Mersey Dreus",
    gender: "Female",
    jobTitle: "Senior Sales Associate",
    language: "Macedonian",
    ssn: "680-61-4401",
    money: "$130.24",
  },
  {
    fullName: "Marie Chazotte",
    gender: "Female",
    jobTitle: "Database Administrator I",
    language: "Khmer",
    ssn: "744-99-5383",
    money: "$162.48",
  },
  {
    fullName: "Jameson Thunnerclef",
    gender: "Male",
    jobTitle: "Database Administrator II",
    language: "Maltese",
    ssn: "258-90-6518",
    money: "$71.69",
  },
  {
    fullName: "Asia Rakestraw",
    gender: "Female",
    jobTitle: "Senior Sales Associate",
    language: "Japanese",
    ssn: "598-95-9606",
    money: "$103.76",
  },
  {
    fullName: "Sydelle Trineman",
    gender: "Female",
    jobTitle: "Systems Administrator II",
    language: "Tok Pisin",
    ssn: "111-09-5003",
    money: "$712.17",
  },
  {
    fullName: "Etta Couve",
    gender: "Female",
    jobTitle: "Developer IV",
    language: "Northern Sotho",
    ssn: "748-39-2810",
    money: "$758.56",
  },
  {
    fullName: "Ardyce Abrahamsson",
    gender: "Female",
    jobTitle: "Help Desk Technician",
    language: "Amharic",
    ssn: "207-15-4266",
    money: "$870.91",
  },
  {
    fullName: "Hersch Perkin",
    gender: "Male",
    jobTitle: "VP Marketing",
    language: "Swati",
    ssn: "157-04-3185",
    money: "$84.40",
  },
  {
    fullName: "Edwina Settle",
    gender: "Female",
    jobTitle: "Legal Assistant",
    language: "Luxembourgish",
    ssn: "388-35-3696",
    money: "$284.32",
  },
  {
    fullName: "Cordelia Tyrrell",
    gender: "Female",
    jobTitle: "Health Coach II",
    language: "Burmese",
    ssn: "529-90-9627",
    money: "$404.62",
  },
  {
    fullName: "Field Rodnight",
    gender: "Male",
    jobTitle: "Junior Executive",
    language: "Kyrgyz",
    ssn: "128-24-7756",
    money: "$728.75",
  },
  {
    fullName: "Wang Rammell",
    gender: "Male",
    jobTitle: "Marketing Assistant",
    language: "Danish",
    ssn: "299-05-1014",
    money: "$145.32",
  },
  {
    fullName: "Lynnell McAllister",
    gender: "Female",
    jobTitle: "Director of Sales",
    language: "Belarusian",
    ssn: "444-29-7780",
    money: "$555.43",
  },
  {
    fullName: "Fifi Langford",
    gender: "Female",
    jobTitle: "Programmer Analyst IV",
    language: "Dzongkha",
    ssn: "424-61-6283",
    money: "$975.55",
  },
  {
    fullName: "Brande Segoe",
    gender: "Female",
    jobTitle: "Senior Financial Analyst",
    language: "Romanian",
    ssn: "877-80-7126",
    money: "$609.79",
  },
  {
    fullName: "Sutherlan Merrifield",
    gender: "Male",
    jobTitle: "Pharmacist",
    language: "Afrikaans",
    ssn: "286-60-7042",
    money: "$796.17",
  },
  {
    fullName: "Henka Coslett",
    gender: "Female",
    jobTitle: "Environmental Specialist",
    language: "Hiri Motu",
    ssn: "383-84-3574",
    money: "$702.93",
  },
  {
    fullName: "Rodie Wetherald",
    gender: "Female",
    jobTitle: "Information Systems Manager",
    language: "Portuguese",
    ssn: "757-56-7453",
    money: "$765.13",
  },
  {
    fullName: "Carmelia Clapston",
    gender: "Female",
    jobTitle: "Cost Accountant",
    language: "Tetum",
    ssn: "651-85-6037",
    money: "$541.10",
  },
  {
    fullName: "Alano Akister",
    gender: "Male",
    jobTitle: "Systems Administrator II",
    language: "Indonesian",
    ssn: "306-99-7377",
    money: "$295.74",
  },
  {
    fullName: "Bastien Mix",
    gender: "Male",
    jobTitle: "Accountant III",
    language: "New Zealand Sign Language",
    ssn: "417-82-4783",
    money: "$442.55",
  },
  {
    fullName: "Yehudit Itscowicz",
    gender: "Male",
    jobTitle: "Internal Auditor",
    language: "Tetum",
    ssn: "821-14-9554",
    money: "$899.58",
  },
  {
    fullName: "Noll de Broke",
    gender: "Male",
    jobTitle: "Junior Executive",
    language: "Kashmiri",
    ssn: "556-33-6013",
    money: "$851.14",
  },
  {
    fullName: "Neall Tanby",
    gender: "Male",
    jobTitle: "Graphic Designer",
    language: "Punjabi",
    ssn: "858-77-3616",
    money: "$740.57",
  },
  {
    fullName: "Lindsey Osban",
    gender: "Male",
    jobTitle: "Research Associate",
    language: "Māori",
    ssn: "771-19-0670",
    money: "$581.73",
  },
  {
    fullName: "Ingra Battyll",
    gender: "Male",
    jobTitle: "Tax Accountant",
    language: "Telugu",
    ssn: "756-02-9176",
    money: "$140.73",
  },
  {
    fullName: "Helge Pickerill",
    gender: "Female",
    jobTitle: "Compensation Analyst",
    language: "Swati",
    ssn: "594-38-9689",
    money: "$958.90",
  },
  {
    fullName: "Wilma Prickett",
    gender: "Female",
    jobTitle: "Geological Engineer",
    language: "Czech",
    ssn: "646-89-0479",
    money: "$861.32",
  },
  {
    fullName: "Barr Fayerman",
    gender: "Male",
    jobTitle: "Staff Scientist",
    language: "Tetum",
    ssn: "749-20-6103",
    money: "$339.34",
  },
  {
    fullName: "Marjory Bumpass",
    gender: "Female",
    jobTitle: "Sales Associate",
    language: "Gagauz",
    ssn: "507-16-5589",
    money: "$511.16",
  },
  {
    fullName: "Carmelia Bodycombe",
    gender: "Female",
    jobTitle: "Technical Writer",
    language: "Irish Gaelic",
    ssn: "794-61-2883",
    money: "$59.78",
  },
  {
    fullName: "Frans Brimilcombe",
    gender: "Male",
    jobTitle: "Budget/Accounting Analyst III",
    language: "Afrikaans",
    ssn: "579-08-3364",
    money: "$387.48",
  },
  {
    fullName: "Goldi Skace",
    gender: "Female",
    jobTitle: "Staff Scientist",
    language: "Dutch",
    ssn: "108-31-0429",
    money: "$909.75",
  },
  {
    fullName: "Evy Nazair",
    gender: "Female",
    jobTitle: "Programmer IV",
    language: "Malay",
    ssn: "461-46-0810",
    money: "$128.47",
  },
  {
    fullName: "Calida Mavin",
    gender: "Female",
    jobTitle: "Analog Circuit Design manager",
    language: "Tok Pisin",
    ssn: "893-61-9693",
    money: "$891.85",
  },
  {
    fullName: "Mace Cothey",
    gender: "Male",
    jobTitle: "Senior Developer",
    language: "Oriya",
    ssn: "121-02-2837",
    money: "$827.87",
  },
  {
    fullName: "Adela Hyatt",
    gender: "Female",
    jobTitle: "Structural Analysis Engineer",
    language: "Khmer",
    ssn: "279-11-8472",
    money: "$271.63",
  },
  {
    fullName: "Archie Waterworth",
    gender: "Male",
    jobTitle: "Help Desk Technician",
    language: "Māori",
    ssn: "670-50-9373",
    money: "$944.96",
  },
  {
    fullName: "Joya Rojel",
    gender: "Female",
    jobTitle: "Product Engineer",
    language: "Fijian",
    ssn: "107-38-6754",
    money: "$183.04",
  },
  {
    fullName: "Isahella Lune",
    gender: "Female",
    jobTitle: "Senior Financial Analyst",
    language: "Northern Sotho",
    ssn: "440-28-9229",
    money: "$460.26",
  },
  {
    fullName: "Tabbie Hatcliffe",
    gender: "Male",
    jobTitle: "Accountant III",
    language: "Chinese",
    ssn: "716-92-1238",
    money: "$133.38",
  },
  {
    fullName: "Zachary Kiltie",
    gender: "Male",
    jobTitle: "Media Manager I",
    language: "Armenian",
    ssn: "275-74-4880",
    money: "$621.15",
  },
  {
    fullName: "Xenos Mathelon",
    gender: "Male",
    jobTitle: "Sales Representative",
    language: "Ndebele",
    ssn: "679-22-6238",
    money: "$557.61",
  },
  {
    fullName: "Clementine Fraczkiewicz",
    gender: "Female",
    jobTitle: "VP Product Management",
    language: "Indonesian",
    ssn: "227-58-3097",
    money: "$905.97",
  },
  {
    fullName: "Ellette Ragbourn",
    gender: "Female",
    jobTitle: "Sales Associate",
    language: "Luxembourgish",
    ssn: "327-45-0445",
    money: "$101.17",
  },
  {
    fullName: "Fleur De Andisie",
    gender: "Female",
    jobTitle: "Product Engineer",
    language: "Hindi",
    ssn: "540-16-9662",
    money: "$261.71",
  },
  {
    fullName: "Lev Costanza",
    gender: "Male",
    jobTitle: "GIS Technical Architect",
    language: "Moldovan",
    ssn: "409-64-7739",
    money: "$663.54",
  },
  {
    fullName: "Jamaal Billyard",
    gender: "Male",
    jobTitle: "Chemical Engineer",
    language: "Arabic",
    ssn: "708-48-7215",
    money: "$470.23",
  },
  {
    fullName: "Nanine Tubridy",
    gender: "Female",
    jobTitle: "Assistant Manager",
    language: "Hungarian",
    ssn: "540-49-9297",
    money: "$134.89",
  },
  {
    fullName: "Bucky Melbourne",
    gender: "Male",
    jobTitle: "Account Executive",
    language: "Montenegrin",
    ssn: "173-19-9604",
    money: "$223.18",
  },
  {
    fullName: "Trina Saurat",
    gender: "Female",
    jobTitle: "Compensation Analyst",
    language: "Lao",
    ssn: "560-89-0893",
    money: "$375.02",
  },
  {
    fullName: "Dexter Carrabot",
    gender: "Male",
    jobTitle: "Quality Engineer",
    language: "Georgian",
    ssn: "363-37-9239",
    money: "$604.92",
  },
  {
    fullName: "Sayer Pettit",
    gender: "Male",
    jobTitle: "Food Chemist",
    language: "Malay",
    ssn: "625-84-0197",
    money: "$417.30",
  },
  {
    fullName: "Salvidor Fenemore",
    gender: "Male",
    jobTitle: "Systems Administrator IV",
    language: "Swedish",
    ssn: "194-06-1897",
    money: "$131.88",
  },
  {
    fullName: "Neal Curton",
    gender: "Male",
    jobTitle: "Web Developer II",
    language: "West Frisian",
    ssn: "652-39-2998",
    money: "$918.64",
  },
  {
    fullName: "Giffy Northing",
    gender: "Male",
    jobTitle: "Database Administrator IV",
    language: "Gagauz",
    ssn: "425-07-6027",
    money: "$667.87",
  },
  {
    fullName: "Florie Pawelczyk",
    gender: "Female",
    jobTitle: "Marketing Manager",
    language: "Armenian",
    ssn: "559-05-6607",
    money: "$442.35",
  },
  {
    fullName: "Samuele Gritsunov",
    gender: "Male",
    jobTitle: "Assistant Professor",
    language: "Bosnian",
    ssn: "868-69-1342",
    money: "$968.89",
  },
  {
    fullName: "Dyann Botler",
    gender: "Female",
    jobTitle: "Analyst Programmer",
    language: "Azeri",
    ssn: "398-23-9974",
    money: "$811.67",
  },
  {
    fullName: "Celene Redier",
    gender: "Female",
    jobTitle: "Legal Assistant",
    language: "Dzongkha",
    ssn: "667-94-4404",
    money: "$181.69",
  },
  {
    fullName: "Glendon Akehurst",
    gender: "Male",
    jobTitle: "Financial Advisor",
    language: "Māori",
    ssn: "888-81-0575",
    money: "$623.15",
  },
  {
    fullName: "Jocelin Binne",
    gender: "Female",
    jobTitle: "Staff Scientist",
    language: "Kyrgyz",
    ssn: "456-07-4564",
    money: "$279.54",
  },
  {
    fullName: "Beverlee Fisk",
    gender: "Female",
    jobTitle: "Senior Editor",
    language: "Hungarian",
    ssn: "124-34-0188",
    money: "$55.33",
  },
  {
    fullName: "Pearce Jindacek",
    gender: "Male",
    jobTitle: "Web Designer II",
    language: "Czech",
    ssn: "629-60-3359",
    money: "$733.87",
  },
  {
    fullName: "Olympe Moden",
    gender: "Female",
    jobTitle: "Assistant Manager",
    language: "Tajik",
    ssn: "891-34-8735",
    money: "$777.97",
  },
  {
    fullName: "Lyndy Abley",
    gender: "Female",
    jobTitle: "Teacher",
    language: "Gujarati",
    ssn: "500-32-2223",
    money: "$181.32",
  },
  {
    fullName: "Brooke Wrankling",
    gender: "Female",
    jobTitle: "Analyst Programmer",
    language: "Dzongkha",
    ssn: "484-49-2081",
    money: "$193.73",
  },
  {
    fullName: "Reube Warland",
    gender: "Male",
    jobTitle: "Registered Nurse",
    language: "Catalan",
    ssn: "168-60-6989",
    money: "$24.58",
  },
  {
    fullName: "Emmerich Nasey",
    gender: "Male",
    jobTitle: "Paralegal",
    language: "Kazakh",
    ssn: "491-80-3161",
    money: "$500.54",
  },
  {
    fullName: "Chelsea Brackley",
    gender: "Female",
    jobTitle: "Actuary",
    language: "Marathi",
    ssn: "636-26-8593",
    money: "$320.04",
  },
  {
    fullName: "Michele Frankland",
    gender: "Female",
    jobTitle: "Junior Executive",
    language: "Fijian",
    ssn: "145-77-6713",
    money: "$526.63",
  },
  {
    fullName: "Juieta Hogbin",
    gender: "Female",
    jobTitle: "Statistician II",
    language: "Fijian",
    ssn: "334-21-9021",
    money: "$902.42",
  },
  {
    fullName: "Dena Bernardinelli",
    gender: "Female",
    jobTitle: "Speech Pathologist",
    language: "Telugu",
    ssn: "216-28-3862",
    money: "$681.82",
  },
  {
    fullName: "Harald Humbles",
    gender: "Male",
    jobTitle: "Quality Control Specialist",
    language: "Tamil",
    ssn: "230-62-1649",
    money: "$567.66",
  },
  {
    fullName: "Ina O'Ruane",
    gender: "Female",
    jobTitle: "Legal Assistant",
    language: "Korean",
    ssn: "134-35-4011",
    money: "$840.48",
  },
  {
    fullName: "Benedicto Stiggles",
    gender: "Male",
    jobTitle: "Account Representative I",
    language: "Belarusian",
    ssn: "705-47-9953",
    money: "$177.83",
  },
  {
    fullName: "Abie Reddy",
    gender: "Male",
    jobTitle: "Senior Developer",
    language: "Hungarian",
    ssn: "104-17-3199",
    money: "$670.43",
  },
  {
    fullName: "Roobbie Sabbin",
    gender: "Female",
    jobTitle: "Account Executive",
    language: "Azeri",
    ssn: "899-60-4375",
    money: "$16.72",
  },
  {
    fullName: "Brennan Viant",
    gender: "Male",
    jobTitle: "Structural Engineer",
    language: "Bengali",
    ssn: "101-59-3657",
    money: "$989.42",
  },
  {
    fullName: "Dick Burkinshaw",
    gender: "Male",
    jobTitle: "Health Coach II",
    language: "Croatian",
    ssn: "480-48-3778",
    money: "$705.21",
  },
  {
    fullName: "Skipton Biggerdike",
    gender: "Male",
    jobTitle: "Teacher",
    language: "Tajik",
    ssn: "678-44-1376",
    money: "$253.09",
  },
  {
    fullName: "Ferdinande Kimmince",
    gender: "Female",
    jobTitle: "Electrical Engineer",
    language: "Lithuanian",
    ssn: "806-56-4853",
    money: "$449.98",
  },
];

//1. 풀네임에서 A, B,C로 시작하는 사람들만 남기기
const q1 = data.filter(
  (x) =>
    x.fullName.startsWith("A") ||
    x.fullName.startsWith("B") ||
    x.fullName.startsWith("C")
);

//2. 성별이 여성이고, 풀네임이 10글자 이상인 사람만 남기기!
const q2 = data.filter((x) => x.gender == "Female" && x.fullName.length >= 10);

//3. 직업이 MANAGER인 사람만 남기고, 풀네일을 이름만 남기기
const q3 = data.filter((x) =>
  x.jobTitle.includes("Manager").map((x) => {
    x.fullName = x.fullName.split(" ")[0];
    return x;
  })
);
